---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ecommstoreappdeployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: ecommstore
 template:
  metadata:
   name: ecommstore
   labels:
     app: ecommstore
  spec:
    containers:
    - name: ecommstorecontainer
      image: websurf500/mysbapp
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: ecommstoresvc
spec:
  type: LoadBalancer
  selector:
   app: ecommstore
  ports:
   - port: 80
     targetPort: 80
...
